name: nfl_score_prediction_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - joblib  # For saving/loading scalers
  - pytorch=1.12  # Specify version compatible with Python 3.10
  - jupyter
  - cpuonly  # Replace with `cudatoolkit=11.3` if using a GPU

# Run "conda env create -f environment.yaml"
# To activate, run "conda activate nfl_score_prediction_env"
